import { Link } from "@tanstack/react-router";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsOfService() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-10 text-foreground">
      {/* Back button */}
      <div className="mb-6">
        <Link
          to="/"
          className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-primary transition-colors"
          data-ocid="terms.back.link"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Dashboard
        </Link>
      </div>

      {/* Header */}
      <div className="flex items-center gap-3 mb-2">
        <FileText className="w-7 h-7 text-primary" />
        <h1 className="text-3xl font-bold text-primary">Terms of Service</h1>
      </div>
      <p className="text-muted-foreground text-sm mb-8">
        Effective Date: April 2026
      </p>

      {/* Risk Disclaimer */}
      <div className="bg-red-950/40 border border-red-500/40 rounded-xl p-6 mb-8">
        <h2 className="text-xl font-extrabold text-red-400 uppercase tracking-wide mb-3">
          ⚠️ Important Risk Disclaimer
        </h2>
        <p className="text-red-200 font-semibold leading-relaxed">
          Alpha Signal AI does <strong>NOT</strong> provide financial advice.
          All signals, analysis, and information are for{" "}
          <strong>educational and informational purposes only</strong>. Trading
          involves significant risk of loss. We are not licensed financial
          advisors. You should never trade with money you cannot afford to lose.
          Past performance does not guarantee future results.
        </p>
      </div>

      {/* Section 1 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          1. Acceptance of Terms
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          By accessing or using Alpha Signal AI ("the Service"), you agree to be
          bound by these Terms of Service. If you do not agree to all the terms
          and conditions of this agreement, you may not access or use the
          Service. These terms apply to all visitors, users, and others who
          access or use the Service.
        </p>
      </section>

      {/* Section 2 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          2. Description of Service
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          Alpha Signal AI is a technical analysis and market data visualization
          platform intended for educational purposes only. The Service provides:
        </p>
        <ul className="list-disc list-inside mt-3 space-y-1.5 text-muted-foreground">
          <li>
            Real-time market data and price feeds from third-party providers
            (Binance, metals.live)
          </li>
          <li>
            Algorithmic trading signals generated by the SFI (Signal Flow
            Intelligence) engine — a rule-based technical indicator
          </li>
          <li>
            AI-powered market commentary generated by Google Gemini — for
            informational and educational purposes only
          </li>
          <li>Educational video content embedded from YouTube</li>
          <li>Macroeconomic calendar data from third-party providers</li>
        </ul>
        <p className="text-muted-foreground leading-relaxed mt-3">
          All signals and analysis provided by the Service are generated by
          automated algorithmic engines and AI systems. They do not represent
          the opinion of licensed financial advisors.
        </p>
      </section>

      {/* Section 3 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          3. No Financial Advice
        </h2>
        <div className="bg-amber-950/40 border border-amber-500/40 rounded-xl p-5 mb-4">
          <p className="text-amber-200 font-semibold leading-relaxed">
            ⚠️ The content provided on Alpha Signal AI is for general
            informational and educational purposes only and does not constitute
            financial, investment, trading, or other types of advice. Nothing on
            this platform should be construed as a recommendation to buy, sell,
            or hold any financial instrument. Trading cryptocurrencies, forex,
            commodities, and other financial instruments involves substantial
            risk of loss and is not suitable for all investors.
          </p>
        </div>
        <p className="text-muted-foreground leading-relaxed">
          You acknowledge that the Service is not a financial advisor, broker,
          dealer, investment advisor, or investment manager as defined under
          applicable laws and regulations. Any decisions you make based on
          information from the Service are your sole responsibility.
        </p>
      </section>

      {/* Section 4 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          4. User Responsibilities
        </h2>
        <p className="text-muted-foreground leading-relaxed mb-3">
          By using the Service, you represent and warrant that:
        </p>
        <ul className="list-disc list-inside space-y-1.5 text-muted-foreground">
          <li>
            You are at least 18 years of age and have the legal capacity to
            enter into this agreement
          </li>
          <li>
            You are solely responsible for all trading decisions you make based
            on information provided by the Service
          </li>
          <li>
            You will comply with all applicable local, state, national, and
            international laws and regulations regarding your use of the Service
            and any trading activities you undertake
          </li>
          <li>
            You will not use the Service for any illegal or unauthorized purpose
          </li>
          <li>
            You understand that trading involves risk and you will not trade
            with funds you cannot afford to lose
          </li>
          <li>
            You acknowledge that past signal performance does not guarantee
            future results
          </li>
        </ul>
      </section>

      {/* Section 5 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          5. Intellectual Property
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          The Service and its original content, features, functionality,
          branding, and design are owned by Alpha Signal AI and are protected by
          international copyright, trademark, patent, trade secret, and other
          intellectual property laws. You may not reproduce, distribute, modify,
          create derivative works of, publicly display, or in any way exploit
          any of the content or materials on the Service without prior written
          consent.
        </p>
      </section>

      {/* Section 6 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          6. Third-Party Services
        </h2>
        <p className="text-muted-foreground leading-relaxed mb-3">
          The Service integrates with and relies on the following third-party
          services, each governed by their own terms of service and privacy
          policies:
        </p>
        <ul className="list-disc list-inside space-y-1.5 text-muted-foreground">
          <li>
            <strong className="text-foreground">Binance</strong> — real-time
            cryptocurrency price data and kline streams
          </li>
          <li>
            <strong className="text-foreground">Google Gemini AI</strong> —
            AI-powered market analysis and commentary
          </li>
          <li>
            <strong className="text-foreground">TradingView</strong> — advanced
            charting widgets and market visualization
          </li>
          <li>
            <strong className="text-foreground">YouTube</strong> — embedded
            educational video content
          </li>
          <li>
            <strong className="text-foreground">Financial Modeling Prep</strong>{" "}
            — macroeconomic calendar data
          </li>
        </ul>
        <p className="text-muted-foreground leading-relaxed mt-3">
          Alpha Signal AI is not responsible for the availability, accuracy, or
          content of these third-party services.
        </p>
      </section>

      {/* Section 7 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          7. Limitation of Liability
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          To the maximum extent permitted by applicable law, Alpha Signal AI and
          its operators, affiliates, partners, officers, employees, agents, and
          service providers shall not be liable for any indirect, incidental,
          special, consequential, or punitive damages, including but not limited
          to loss of profits, loss of data, loss of business, or any financial
          losses arising from your trading activities or your use of, or
          inability to use, the Service. This includes any losses incurred by
          following or acting on signals, analysis, or information provided by
          the Service. Your use of the Service is at your sole risk.
        </p>
      </section>

      {/* Section 8 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          8. Changes to Terms
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          We reserve the right to modify or replace these Terms of Service at
          any time at our sole discretion. We will provide notice of any
          significant changes by updating the effective date at the top of this
          page. Your continued use of the Service after any changes constitutes
          your acceptance of the new Terms of Service. It is your responsibility
          to review these terms periodically for changes.
        </p>
      </section>

      {/* Section 9 */}
      <section className="mb-8">
        <h2 className="text-xl font-bold mb-3 border-b border-border pb-2">
          9. Contact
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          If you have any questions about these Terms of Service, please contact
          us at:{" "}
          <a
            href="mailto:prakash.brjn01@gmail.com"
            className="text-primary hover:underline font-mono"
          >
            prakash.brjn01@gmail.com
          </a>
        </p>
      </section>

      {/* Footer note */}
      <div className="mt-10 pt-6 border-t border-border">
        <p className="text-xs text-muted-foreground/60 text-center italic">
          These terms are required for Google Play Store compliance.
        </p>
        <div className="text-[10px] text-muted-foreground text-center mt-3 space-x-2">
          <span>© {new Date().getFullYear()} Alpha Signal AI</span>
          <span>·</span>
          <a href="/privacy-policy" className="text-primary hover:underline">
            Privacy Policy
          </a>
          <span>·</span>
          <a href="/terms" className="text-primary hover:underline">
            Terms of Service
          </a>
        </div>
      </div>
    </div>
  );
}
