/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AISignal = IDL.Record({
  'direction' : IDL.Text,
  'takeProfit' : IDL.Float64,
  'reasoning' : IDL.Text,
  'stopLoss' : IDL.Float64,
  'entryPrice' : IDL.Float64,
  'confidence' : IDL.Nat,
  'riskLevel' : IDL.Text,
  'symbol' : IDL.Text,
});
export const GeminiAnalysis = IDL.Record({
  'marketBias' : IDL.Text,
  'confidence' : IDL.Nat,
  'strategicInsight' : IDL.Text,
  'signal' : IDL.Text,
  'rawText' : IDL.Text,
});
export const ResearchReport = IDL.Record({
  'ticker' : IDL.Text,
  'assetType' : IDL.Text,
  'executiveSummary' : IDL.Text,
  'fundamentalHealth' : IDL.Text,
  'technicalOutlook' : IDL.Text,
  'priceTargets' : IDL.Text,
  'riskAssessment' : IDL.Text,
  'keyCatalysts' : IDL.Text,
  'overallRating' : IDL.Text,
  'rawText' : IDL.Text,
});
export const GeminiResearchResult = IDL.Record({
  'symbol' : IDL.Text,
  'bias' : IDL.Text,
  'confidence' : IDL.Nat,
  'analysis' : IDL.Text,
  'entry' : IDL.Float64,
  'tp' : IDL.Float64,
  'sl' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'subscriptionTier' : IDL.Text,
  'email' : IDL.Text,
});
export const Candle = IDL.Record({
  'low' : IDL.Float64,
  'high' : IDL.Float64,
  'close' : IDL.Float64,
  'open' : IDL.Float64,
  'volume' : IDL.Float64,
  'timestamp' : IDL.Int,
});
export const LiquidationZone = IDL.Record({
  'priceLevel' : IDL.Float64,
  'longLiquidations' : IDL.Float64,
  'shortLiquidations' : IDL.Float64,
  'intensity' : IDL.Nat,
});
export const MarketAsset = IDL.Record({
  'change24h' : IDL.Float64,
  'name' : IDL.Text,
  'volume' : IDL.Float64,
  'low24h' : IDL.Float64,
  'high24h' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const MarketSentiment = IDL.Record({
  'sentiment' : IDL.Text,
  'fearGreedLabel' : IDL.Text,
  'fearGreedIndex' : IDL.Nat,
});
export const PerformanceStats = IDL.Record({
  'bestTrade' : IDL.Float64,
  'worstTrade' : IDL.Float64,
  'totalTrades' : IDL.Nat,
  'avgLoss' : IDL.Float64,
  'totalPnl' : IDL.Float64,
  'winRate' : IDL.Float64,
  'avgWin' : IDL.Float64,
});
export const SmcSignal = IDL.Record({
  'priceLevel' : IDL.Float64,
  'direction' : IDL.Text,
  'description' : IDL.Text,
  'strength' : IDL.Nat,
  'symbol' : IDL.Text,
  'signalType' : IDL.Text,
});
export const Gainer = IDL.Record({
  'name' : IDL.Text,
  'price' : IDL.Float64,
  'changePercent' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const TradeRecord = IDL.Record({
  'id' : IDL.Nat,
  'pnl' : IDL.Float64,
  'direction' : IDL.Text,
  'pnlPercent' : IDL.Float64,
  'timestamp' : IDL.Int,
  'entryPrice' : IDL.Float64,
  'exitPrice' : IDL.Float64,
  'outcome' : IDL.Text,
  'symbol' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'analyzeWithGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
  'researchWithGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getSentimentFromNews' : IDL.Func(
      [IDL.Vec(IDL.Text)],
      [GeminiAnalysis],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAISignals' : IDL.Func([], [IDL.Vec(AISignal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCandlestickData' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(Candle)],
      ['query'],
    ),
  'getLiquidationData' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(LiquidationZone)],
      ['query'],
    ),
  'getMarketData' : IDL.Func([], [IDL.Vec(MarketAsset)], ['query']),
  'getMarketSentiment' : IDL.Func([], [MarketSentiment], ['query']),
  'getPerformanceStats' : IDL.Func([], [PerformanceStats], ['query']),
  'getSmcSignals' : IDL.Func([], [IDL.Vec(SmcSignal)], ['query']),
  'getTopGainers' : IDL.Func([], [IDL.Vec(Gainer)], ['query']),
  'getTopLosers' : IDL.Func([], [IDL.Vec(Gainer)], ['query']),
  'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'refreshMarketData' : IDL.Func([], [IDL.Vec(MarketAsset)], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AISignal = IDL.Record({
    'direction' : IDL.Text,
    'takeProfit' : IDL.Float64,
    'reasoning' : IDL.Text,
    'stopLoss' : IDL.Float64,
    'entryPrice' : IDL.Float64,
    'confidence' : IDL.Nat,
    'riskLevel' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const GeminiAnalysis = IDL.Record({
    'marketBias' : IDL.Text,
    'confidence' : IDL.Nat,
    'strategicInsight' : IDL.Text,
    'signal' : IDL.Text,
    'rawText' : IDL.Text,
  });
  const ResearchReport = IDL.Record({
    'ticker' : IDL.Text,
    'assetType' : IDL.Text,
    'executiveSummary' : IDL.Text,
    'fundamentalHealth' : IDL.Text,
    'technicalOutlook' : IDL.Text,
    'priceTargets' : IDL.Text,
    'riskAssessment' : IDL.Text,
    'keyCatalysts' : IDL.Text,
    'overallRating' : IDL.Text,
    'rawText' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'subscriptionTier' : IDL.Text,
    'email' : IDL.Text,
  });
  const Candle = IDL.Record({
    'low' : IDL.Float64,
    'high' : IDL.Float64,
    'close' : IDL.Float64,
    'open' : IDL.Float64,
    'volume' : IDL.Float64,
    'timestamp' : IDL.Int,
  });
  const LiquidationZone = IDL.Record({
    'priceLevel' : IDL.Float64,
    'longLiquidations' : IDL.Float64,
    'shortLiquidations' : IDL.Float64,
    'intensity' : IDL.Nat,
  });
  const MarketAsset = IDL.Record({
    'change24h' : IDL.Float64,
    'name' : IDL.Text,
    'volume' : IDL.Float64,
    'low24h' : IDL.Float64,
    'high24h' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const MarketSentiment = IDL.Record({
    'sentiment' : IDL.Text,
    'fearGreedLabel' : IDL.Text,
    'fearGreedIndex' : IDL.Nat,
  });
  const PerformanceStats = IDL.Record({
    'bestTrade' : IDL.Float64,
    'worstTrade' : IDL.Float64,
    'totalTrades' : IDL.Nat,
    'avgLoss' : IDL.Float64,
    'totalPnl' : IDL.Float64,
    'winRate' : IDL.Float64,
    'avgWin' : IDL.Float64,
  });
  const SmcSignal = IDL.Record({
    'priceLevel' : IDL.Float64,
    'direction' : IDL.Text,
    'description' : IDL.Text,
    'strength' : IDL.Nat,
    'symbol' : IDL.Text,
    'signalType' : IDL.Text,
  });
  const Gainer = IDL.Record({
    'name' : IDL.Text,
    'price' : IDL.Float64,
    'changePercent' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const TradeRecord = IDL.Record({
    'id' : IDL.Nat,
    'pnl' : IDL.Float64,
    'direction' : IDL.Text,
    'pnlPercent' : IDL.Float64,
    'timestamp' : IDL.Int,
    'entryPrice' : IDL.Float64,
    'exitPrice' : IDL.Float64,
    'outcome' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'analyzeWithGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
    'researchWithGemini' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getSentimentFromNews' : IDL.Func(
        [IDL.Vec(IDL.Text)],
        [GeminiAnalysis],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAISignals' : IDL.Func([], [IDL.Vec(AISignal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCandlestickData' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(Candle)],
        ['query'],
      ),
    'getLiquidationData' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(LiquidationZone)],
        ['query'],
      ),
    'getMarketData' : IDL.Func([], [IDL.Vec(MarketAsset)], ['query']),
    'getMarketSentiment' : IDL.Func([], [MarketSentiment], ['query']),
    'getPerformanceStats' : IDL.Func([], [PerformanceStats], ['query']),
    'getSmcSignals' : IDL.Func([], [IDL.Vec(SmcSignal)], ['query']),
    'getTopGainers' : IDL.Func([], [IDL.Vec(Gainer)], ['query']),
    'getTopLosers' : IDL.Func([], [IDL.Vec(Gainer)], ['query']),
    'getTradeHistory' : IDL.Func([], [IDL.Vec(TradeRecord)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'refreshMarketData' : IDL.Func([], [IDL.Vec(MarketAsset)], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };
