/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AISignal {
  'direction' : string,
  'takeProfit' : number,
  'reasoning' : string,
  'stopLoss' : number,
  'entryPrice' : number,
  'confidence' : bigint,
  'riskLevel' : string,
  'symbol' : string,
}
export interface Candle {
  'low' : number,
  'high' : number,
  'close' : number,
  'open' : number,
  'volume' : number,
  'timestamp' : bigint,
}
export interface Gainer {
  'name' : string,
  'price' : number,
  'changePercent' : number,
  'symbol' : string,
}
export interface GeminiAnalysis {
  'marketBias' : string,
  'confidence' : bigint,
  'strategicInsight' : string,
  'signal' : string,
  'rawText' : string,
}
export interface LiquidationZone {
  'priceLevel' : number,
  'longLiquidations' : number,
  'shortLiquidations' : number,
  'intensity' : bigint,
}
export interface MarketAsset {
  'change24h' : number,
  'name' : string,
  'volume' : number,
  'low24h' : number,
  'high24h' : number,
  'price' : number,
  'symbol' : string,
}
export interface MarketSentiment {
  'sentiment' : string,
  'fearGreedLabel' : string,
  'fearGreedIndex' : bigint,
}
export interface PerformanceStats {
  'bestTrade' : number,
  'worstTrade' : number,
  'totalTrades' : bigint,
  'avgLoss' : number,
  'totalPnl' : number,
  'winRate' : number,
  'avgWin' : number,
}
export interface SmcSignal {
  'priceLevel' : number,
  'direction' : string,
  'description' : string,
  'strength' : bigint,
  'symbol' : string,
  'signalType' : string,
}
export interface TradeRecord {
  'id' : bigint,
  'pnl' : number,
  'direction' : string,
  'pnlPercent' : number,
  'timestamp' : bigint,
  'entryPrice' : number,
  'exitPrice' : number,
  'outcome' : string,
  'symbol' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'subscriptionTier' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface ResearchReport {
  'ticker' : string,
  'assetType' : string,
  'executiveSummary' : string,
  'fundamentalHealth' : string,
  'technicalOutlook' : string,
  'priceTargets' : string,
  'riskAssessment' : string,
  'keyCatalysts' : string,
  'overallRating' : string,
  'rawText' : string,
}

export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'analyzeWithGemini' : ActorMethod<[string], string>,
  'researchWithGemini' : ActorMethod<[string], string>,
  'getSentimentFromNews' : ActorMethod<[Array<string>], GeminiAnalysis>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAISignals' : ActorMethod<[], Array<AISignal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCandlestickData' : ActorMethod<[string, string], Array<Candle>>,
  'getLiquidationData' : ActorMethod<[string], Array<LiquidationZone>>,
  'getMarketData' : ActorMethod<[], Array<MarketAsset>>,
  'getMarketSentiment' : ActorMethod<[], MarketSentiment>,
  'getPerformanceStats' : ActorMethod<[], PerformanceStats>,
  'getSmcSignals' : ActorMethod<[], Array<SmcSignal>>,
  'getTopGainers' : ActorMethod<[], Array<Gainer>>,
  'getTopLosers' : ActorMethod<[], Array<Gainer>>,
  'getTradeHistory' : ActorMethod<[], Array<TradeRecord>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'refreshMarketData' : ActorMethod<[], Array<MarketAsset>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
